bonus:
  service:
    type: ClusterIP
    port: 8050
    image: ananasiika/bonus-service:latest
    env:
      DATA_BASE_PORT: 5432
      DATA_BASE_NAME: postgres
      DATA_BASE_USER: postgres
      DATA_BASE_PASS: postgres
      DATA_BASE_HOST: postgres

tickets:
  service:
    type: ClusterIP
    port: 8070
    image: ananasiika/ticket-service:latest
    env:
      DATA_BASE_PORT: 5432
      DATA_BASE_NAME: postgres
      DATA_BASE_USER: postgres
      DATA_BASE_PASS: postgres
      DATA_BASE_HOST: postgres

flights:
  service:
    type: ClusterIP
    port: 8060
    image: ananasiika/flight-service:latest
    env:
      DATA_BASE_PORT: 5432
      DATA_BASE_NAME: postgres
      DATA_BASE_USER: postgres
      DATA_BASE_PASS: postgres
      DATA_BASE_HOST: postgres

gateway:
  service:
    type: NodePort
    port: 8080
    nodePort: 30000
    image: ananasiika/gateway-service:latest
    isGateway: true
    env:
      Services__FlightService: "http://flights"   
      Services__BonusService: "http://bonus"    
      Services__TicketService: "http://tickets" 