apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-service
  labels:
    app: flight-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-service
  template:
    metadata:
      labels:
        app: flight-service
    spec:
      containers:
      - name: flight-service
        image: ${{ secrets.DOCKERHUB_USERNAME }}/flight-service:latest
        ports:
        - containerPort: 8060
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Host=postgresql;Port=5432;Database=flights;Username=postgres;Password=postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: flight-service
spec:
  selector:
    app: flight-service
  ports:
  - port: 8060
    targetPort: 8060