apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
  labels:
    app: ticket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      containers:
      - name: ticket-service
        image: ${{ secrets.DOCKERHUB_USERNAME }}/ticket-service:latest
        ports:
        - containerPort: 8070
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Host=postgresql;Port=5432;Database=tickets;Username=postgres;Password=postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-service
spec:
  selector:
    app: ticket-service
  ports:
  - port: 8070
    targetPort: 8070